
obstacle_range: 6.0
raytrace_range: 6.0
robot_radius: 0.1175
min_obstacle_height: 0.0
footprint_padding: 0
# footprint: [[0.15, 0.15], [0.15, -0.15], [-0.15, -0.15], [-0.15, 0.14]]
map_topic: /map
global_frame: map
robot_base_frame: base_footprint
always_send_full_costmap: true
subscribe_to_updates: true

obstacles:
  observation_sources: laser_scan_sensor
  laser_scan_sensor: {sensor_frame: camera_link, data_type: LaserScan, topic: /camera/scan, marking: true, clearing: true}
  # point_cloud_sensor: {sensor_frame: camera_link, data_type: PointCloud, topic: /camera/depth/image_raw, marking: true, clearing: true}

static:
  map_topic: /map
  subscribe_to_updates: true

plugins:
  - {name: static,           type: "costmap_2d::StaticLayer"}
  - {name: obstacles,        type: "costmap_2d::ObstacleLayer"}
  - {name: inflation,        type: "costmap_2d::InflationLayer"}