local_costmap:
  update_frequency: 2.5
  publish_frequency: 2.5
  transform_tolerance: 0.25
  static_map: false
  rolling_window: true
  width: 4
  height: 4
  resolution: 0.01
  inflation_radius: 0.1
  inflation:
    inflation_radius: 0.1
    cost_scaling_factor: 0.5


